### ISSUE TITLE
ImportError running cfn-signal

### ISSUE THREAD

**Issue by gianrubio** [coreos/awscli#3]
```
$ docker run -ti quay.io/coreos/awscli:edge bash
bash-4.3# cfn-signal
Traceback (most recent call last):
  File "/usr/bin/cfn-signal", line 19, in <module>
    from cfnbootstrap.cfn_client import CloudFormationClient
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/cfn_client.py", line 24, in <module>
    from cfnbootstrap import aws_client, util
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/aws_client.py", line 23, in <module>
    from cfnbootstrap import util
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/util.py", line 16, in <module>
    import endpoint_tool
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/endpoint_tool.py", line 16, in <module>
    from resources import documents
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/resources/documents/__init__.py", line 31, in <module>
    import pkg_resources
ImportError: No module named pkg_resources
```

**Comment by colhom** [comment]
Fixed by #4
